version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gjftek9ma4z6"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Environment=\"dev\" ExportPrefix=\"MyApp\" BillingMode=\"PROVISIONED\" DefaultLambdaTimeout=\"3\" DefaultLambdaMemory=\"128\" TTLAttribute=\"None\" CDNHostedZoneId=\"Z2FDTNDATAQYW2\" DomainName=\"acloudtiger.com\""
